event_inherited();
movespeed = 2;
vsp = 0;
hsp = 0;
state = platformer_state;
start_state = state;
hp = 10;
atk = 2;
s_idle = spr_player_right_idle;
s_move = spr_player_right_move;
s_atk = spr_player_right_atk;
s_dj = spr_player_r_j_right;
grav = 0.5;
maxJumps = 1;
jumps = maxJumps;
rolling = false;
roll_scale_factor = 2;
